
set(FEDORA 0)

include(FindDetectFiles.cmake)


if(CAT AND SED)
    if(DEFINED FEDORA)
        if(EXISTS /etc/os-release)
            if(${OS_RELEASE_DISTRO} MATCHES "Fedora")
                set(FEDORA 1)
            else()
                set(FEDORA 0)
            endif()
        elseif(EXISTS /etc/fedora-release)
            exec_program(${CAT} ARGS /etc/fedora-release OUTPUT_VARIABLE DISTRO_RELEASE_TEXT)
            exec_program(${SED} ARGS ${DISTRO_RELEASE_REGEX} ${DISTRO_RELEASE_TEXT} OUTPUT_VARIABLE DISTRO_RELEASE_DISTRO)
            string(FIND ${DISTRO_RELEASE_DISTRO} "Fedora" FEDORA_POSITION)
            if(${FEDORA_POSITION} GREATER -1)
                set(FEDORA 1)
            else()
                set(FEDORA 0)
            endif()
        else()
            if(${LSB_RELEASE_DISTRO} MATCHES "Fedora")
                set(FEDORA 1)
            else()
                set(FEDORA 0)
            endif()
        endif()
    endif()
endif()


unset(OS_RELEASE_DISTRO_REGEX)
unset(DISTRO_RELEASE_REGEX)
unset(LSB_RELEASE_REGEX)
unset(TRIM_VARIABLE_REGEX)
unset(REMOVE_NOT_MATCHED_OS)
unset(REMOVE_NOT_MATCHED_LSB)
