".page_break {page-break-before: always;}\n"
"h1 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 16px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold;\n"
"}\n"
"h2 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 14px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold;\n"
"}\n"
"h3 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 12px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold; \n"
"}\n"
"h4 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 10px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold;\n"
"}\n"
".towaryN { \n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 8px;\n"
" color: #000000; \n"
" font-style: normal;\n"
" font-weight: bold;\n"
"}\n"
".towaryList {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 8px;\n"
" color: #000000; font-style: normal;\n"
"}\n"
"\n"
".stawki {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 10px;\n"
" font-weight: normal; \n"
" color: #000000; font-style: normal;\n"
"}\n"
"\n"
"h5 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 10px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold; \n"
"}\n"
"h6 {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 8px;\n"
" color: #000000; font-style: normal;\n"
" font-weight: bold; \n"
"}\n"
"\n"
".goods {\n"
" border: 1px #FFFFFF ridge;\n"
" border-spacing: 0px;\n"
"}\n"
"\n"
".podpisy {\n"
" font-family: Verdana, Tahoma, Arial;\n"
" font-size: 8px;\n"
" color: #000000; font-style: normal;\n"
"}\n"
